// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

/************************************************************/
/**
 * 
 */
public class Horca {
	/**
	 * 
	 */
	public int Intentos;
	/**
	 * Sirve para saber si ha ganado o perdido si ha ganado es boolean true y si ha perdido boolean false.
	 */
	public boolean Fin;
};
