// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

/************************************************************/
/**
 * 
 */
public class Partida {
	/**
	 * 
	 */
	public String Palabra;
	/**
	 * 
	 */
	public char Letras;
	/**
	 * 
	 */
	public String Pista;
	/**
	 * 
	 */
	public int Intentos;

	/**
	 * 
	 */
	public void GeneraPalabra() {
	}

	/**
	 * 
	 */
	public void GeneraPista() {
	}

	/**
	 * 
	 */
	public void VerificarLetra() {
	}

	/**
	 * 
	 */
	public void VerificarFin() {
	}
};
